version: "3.8"
services:
  server:
    build:
      context: ./server
    image: 493549863063.dkr.ecr.us-west-1.amazonaws.com/nucampsite-aws-docker:nucampsite-aws-server
    ports:
      - "5443:5443"
    container_name: nucampsiteserver
    networks:
        - nucamp
  client:
    environment:
      SKIP_PREFLIGHT_CHECK: "true"
    build:
      context: ./client
    image: 493549863063.dkr.ecr.us-west-1.amazonaws.com/nucampsite-aws-docker:nucampsite-aws-client
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    networks:
        - nucamp
  mongodb:
    image: 493549863063.dkr.ecr.us-west-1.amazonaws.com/nucampsite-aws-docker:nucampsite-aws-mongo
    restart: always
    container_name: mongodb
    # volumes:
    #     - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth
    networks:
        - nucamp
networks:
    nucamp:
        driver: bridge
#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