version: "3.8"
services:
  server:
    image: "patchkientz/nucampsite-aws-server:latest"
    ports:
      - "5000:5000"
      - "5443:5443"
    container_name: nucampsiteserver
    networks:
        - nucamp
  client:
    image: "patchkientz/nucampsite-aws-client:latest"
    ports:
      - "80:80"
      - "443:443"
    container_name: client
    stdin_open: true
    networks:
        - nucamp
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
        - ./data:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth
    networks:
        - nucamp
networks:
    nucamp:
        driver: bridge
